### ISSUE TITLE
Data Incomplete Vialidades Primarias

### ISSUE THREAD

**Issue by juliogontor** [CodeandoGuadalajara/IMEPLAN#3]
La capa de vialidades primarias y estructura vial está incompleta, falta el municipio de GDL, quizá por que los planes de GDL no están aprobados, sería bueno ver si GDL los proporciona y armar una redvial con sentidos de calles abierta y complementarla en OSM.

**Comment by basicavisual** [comment]
Pedir los datos puede ser una actividad de la siguiente CHN

**Comment by juliogontor** [comment]
Estos datos ya los tiene guadalajara en su información y openstreetmap.
